name : Prediksi Customer Churn pada Perusahaan Telecom
services:
  streamlit:
    build: docker/streamlit
    image: axel/Telecom_Pred
    container_name : streamlit_frontend
    depends_on :
      - api
    ports :
      - 8501:8501
    volumes :
      - ./:/home/
  api:
    build: docker/api
    image: axel/Telecom_Pred
    container_name : api_backend
    ports :
      - 8080:8080
    volumes :
      - ./:/home/