dataset_dir: data/raw/
float64_columns:
- DataUsage
- DayMins
- MonthlyCharge
- OverageFee
- RoamMins
int32_columns:
- ID
- AccountWeeks
- CustServCalls
- DayCalls
label: Churn
label_categories:
- Ya
- Tidak
- Tidak Tahu
label_categories_new:
- Ya
- Tidak
missing_value_AccountWeeks:
  Tidak: 101
  Ya: 103
missing_value_CustServCalls: 1
missing_value_DataUsage:
  Tidak: 0.8882406471183009
  Ya: 0.5436498516320476
missing_value_DayCalls: 101
missing_value_DayMins: 179.63004735256132
missing_value_MonthlyCharge: 53
missing_value_OverageFee: 10.12
missing_value_RoamMins: 10.12
missing_value_co: 11
missing_value_no2: 18
missing_value_o3: 29
missing_value_so2: 35
object_columns:
- ContractRenewal
- DataPlan
- Churn
predictors:
- AccountWeeks
- ContractRenewal
- DataPlan
- DataUsage
- CustServCalls
- DayMins
- DayCalls
- MonthlyCharge
- OverageFee
- RoamMins
range_AccountWeeks:
- -1
- 243
range_Churn:
- Tidak
- Ya
range_ContractRenewal:
- 'No'
- 'Yes'
range_CustServCalls:
- -1
- 9
range_DataPlan:
- 'No'
- 'Yes'
range_DataUsage:
- -1
- 5.4
range_DayCalls:
- -1
- 165
range_DayMins:
- -1
- 350.8
range_ID:
- 0
- 3333
range_MonthlyCharge:
- -1
- 111.3
range_OverageFee:
- 0
- 18.19
range_RoamMins:
- -1
- 20
